plot = true

[peaker]

# Set to true to read from the peak cache if the cache is newer.
# It always writes to a cache file anyway.
cache = true

# picker = "simple"
picker = "hires"

debug = 0 # No plots, yet
# debug = 1 # Plot every spectrum
# debug = 2 # Plot everything including windowed peak detection results

# Total ion count threshold to ignore spectra with too lower ion counts
tic_threshold = 1e3

[peaker.hires]

signal_to_noise = 10.0

[peaker.simple]

# Simply removing noise data.
distance = 0.03
threshold = 15
# When a "peak" reaches this width, treat it as multiple peaks.
max_peak_width = 0.06

[feature_finder]

cache = true

debug = 1

# See https://openms.de/current_doxygen/html/classOpenMS_1_1FeatureFinderAlgorithmPicked.html#details
min_score = 0.5

[feature_finder.mass_trace]

mz_tolerance = 0.02
min_spectra = 3
slope_bound = 0.1

[feature_finder.isotopic_pattern]

charge_low = 1
charge_high = 4
mz_tolerance = 0.01
intensity_percentage = 50.0

[peptide_searcher]

[peptide_searcher.library]

library_file = "/path/to/Proteins.fasta"
cache = true

# Modifications, only IAA supported yet
modifications = "IAA"
# Only trypsin supported yet
digestion = "trypsin"
max_digestion_misses = 3

[peptide_searcher.search]

cache = true
mass_error_value = 0.02

[matcher]

# cache = false # Cache not supported yet.
debug = 0
score_threshold = 0.5

range = [ 2.5, 4.0 ]
selected = [
    512.0,
]
selected_delta = 1.0
